/*
 * CreateBackupJob.java
 *
 * Created on __DATE__, __TIME__
 */

package frame;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.xml.parsers.ParserConfigurationException;

import org.opendedup.util.date.WeekPolicy;

import frame.threads.VolumeInfoShowThread;

import xjtu.dedup.backupmngt.BackupApp;
import xjtu.dedup.multithread.BackupClient;

/**
 *
 * @author  __USER__
 */
public class CreateBackupJob extends javax.swing.JFrame {

	//backup job record
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
	String backupJobname = null;
	String backupSrc = null;
	String backupVolume = null;
	WeekPolicy weekp = new WeekPolicy();//每天的备份类型
	int type = -1;//备份类型：0：全备份 1：增量备份 2：差异备份
	long backupFilesLength = 0l; //备份数据大小
	long backupJobFilesCount = 01;//备份任务所含文件数
	String backupDate;

	BackupApp ba = new BackupApp();//backup object 

	public static void setTextField9(String vol_name) {
		jTextField9.setText(vol_name);
	}

	/** Creates new form CreateBackupJob */
	public CreateBackupJob() {
		this.setTitle("制定备份任务");
		initComponents();
		Dimension d = Toolkit.getDefaultToolkit().getScreenSize();
		this.setSize(760, 600);
		this.setLocation(d.width / 2 - 760 / 2, d.height / 2 - 600 / 2);
		try {
			javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager
					.getSystemLookAndFeelClassName());
			javax.swing.SwingUtilities.updateComponentTreeUI(this);
		} catch (Exception e) {
			// TODO: handle exception
			e.printStackTrace();
			try {
				javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager
						.getCrossPlatformLookAndFeelClassName());
				javax.swing.SwingUtilities.updateComponentTreeUI(this);
			} catch (Exception e1) {
				// TODO: handle exception
				e1.printStackTrace();
			}
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jFileChooser1 = new javax.swing.JFileChooser();
		jPanel27 = new javax.swing.JPanel();
		jSeparator8 = new javax.swing.JSeparator();
		jPanel28 = new javax.swing.JPanel();
		jLabel20 = new javax.swing.JLabel();
		jPanel29 = new javax.swing.JPanel();
		jLabel21 = new javax.swing.JLabel();
		jTextField8 = new javax.swing.JTextField();
		jPanel30 = new javax.swing.JPanel();
		jLabel22 = new javax.swing.JLabel();
		jButton14 = new javax.swing.JButton();
		jPanel36 = new javax.swing.JPanel();
		jPanel37 = new javax.swing.JPanel();
		jPanel38 = new javax.swing.JPanel();
		jScrollPane1 = new javax.swing.JScrollPane();
		jTextArea1 = new javax.swing.JTextArea();
		jPanel39 = new javax.swing.JPanel();
		jPanel31 = new javax.swing.JPanel();
		jLabel23 = new javax.swing.JLabel();
		jButton15 = new javax.swing.JButton();
		jTextField9 = new javax.swing.JTextField();
		jPanel32 = new javax.swing.JPanel();
		jLabel24 = new javax.swing.JLabel();
		jPanel40 = new javax.swing.JPanel();
		jCheckBox5 = new javax.swing.JCheckBox();
		jCheckBox6 = new javax.swing.JCheckBox();
		jCheckBox7 = new javax.swing.JCheckBox();
		jPanel33 = new javax.swing.JPanel();
		jLabel25 = new javax.swing.JLabel();
		jPanel41 = new javax.swing.JPanel();
		jRadioButton3 = new javax.swing.JRadioButton();
		jRadioButton4 = new javax.swing.JRadioButton();
		jRadioButton5 = new javax.swing.JRadioButton();
		jRadioButton6 = new javax.swing.JRadioButton();
		jPanel34 = new javax.swing.JPanel();
		jPanel42 = new javax.swing.JPanel();
		jPanel43 = new javax.swing.JPanel();
		jRadioButton7 = new javax.swing.JRadioButton();
		jRadioButton8 = new javax.swing.JRadioButton();
		jRadioButton9 = new javax.swing.JRadioButton();
		jPanel44 = new javax.swing.JPanel();
		jPanel35 = new javax.swing.JPanel();
		jButton16 = new javax.swing.JButton();
		jButton17 = new javax.swing.JButton();
		jSeparator6 = new javax.swing.JSeparator();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		addWindowListener(new java.awt.event.WindowAdapter() {
			public void windowClosing(java.awt.event.WindowEvent evt) {
				formWindowClosing(evt);
			}
		});
		getContentPane().setLayout(
				new javax.swing.BoxLayout(getContentPane(),
						javax.swing.BoxLayout.LINE_AXIS));

		jPanel27.setPreferredSize(new java.awt.Dimension(840, 640));
		jPanel27.setLayout(new javax.swing.BoxLayout(jPanel27,
				javax.swing.BoxLayout.PAGE_AXIS));
		jPanel27.add(jSeparator8);

		jLabel20.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel20.setText("\u5907\u4efd\u4f5c\u4e1a\u5b9a\u5236");

		javax.swing.GroupLayout jPanel28Layout = new javax.swing.GroupLayout(
				jPanel28);
		jPanel28.setLayout(jPanel28Layout);
		jPanel28Layout.setHorizontalGroup(jPanel28Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel28Layout.createSequentialGroup().addGap(279, 279, 279)
						.addComponent(jLabel20).addContainerGap(363,
								Short.MAX_VALUE)));
		jPanel28Layout.setVerticalGroup(jPanel28Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel28Layout.createSequentialGroup().addGap(19, 19, 19)
						.addComponent(jLabel20).addContainerGap(37,
								Short.MAX_VALUE)));

		jPanel27.add(jPanel28);

		jPanel29.setMaximumSize(new java.awt.Dimension(32767, 200));
		jPanel29.setPreferredSize(new java.awt.Dimension(240, 40));
		jPanel29.setLayout(new javax.swing.BoxLayout(jPanel29,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel21.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel21.setText("\u5907\u4efd\u4efb\u52a1\u540d");
		jLabel21.setMaximumSize(new java.awt.Dimension(240, 21));
		jLabel21.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel29.add(jLabel21);

		jTextField8.setMaximumSize(new java.awt.Dimension(420, 21));
		jTextField8.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel29.add(jTextField8);

		jPanel27.add(jPanel29);

		jPanel30.setMaximumSize(new java.awt.Dimension(32767, 480));
		jPanel30.setPreferredSize(new java.awt.Dimension(181, 40));
		jPanel30.setLayout(new javax.swing.BoxLayout(jPanel30,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel22.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel22.setText("\u5907\u4efd\u6e90\u6587\u4ef6");
		jLabel22.setMaximumSize(new java.awt.Dimension(240, 21));
		jLabel22.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel30.add(jLabel22);

		jButton14.setFont(new java.awt.Font("宋体", 0, 14));
		jButton14.setText("\u9009\u62e9");
		jButton14.setMaximumSize(new java.awt.Dimension(80, 25));
		jButton14.setMinimumSize(new java.awt.Dimension(40, 25));
		jButton14.setPreferredSize(new java.awt.Dimension(0, 25));
		jButton14.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton14ActionPerformed(evt);
			}
		});
		jPanel30.add(jButton14);

		jPanel27.add(jPanel30);

		jPanel36.setLayout(new javax.swing.BoxLayout(jPanel36,
				javax.swing.BoxLayout.LINE_AXIS));

		jPanel37.setMaximumSize(new java.awt.Dimension(240, 240));
		jPanel37.setPreferredSize(new java.awt.Dimension(240, 100));

		javax.swing.GroupLayout jPanel37Layout = new javax.swing.GroupLayout(
				jPanel37);
		jPanel37.setLayout(jPanel37Layout);
		jPanel37Layout.setHorizontalGroup(jPanel37Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 240,
				Short.MAX_VALUE));
		jPanel37Layout.setVerticalGroup(jPanel37Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		jPanel36.add(jPanel37);

		jPanel38.setMaximumSize(new java.awt.Dimension(420, 240));
		jPanel38.setMinimumSize(new java.awt.Dimension(0, 0));
		jPanel38.setPreferredSize(new java.awt.Dimension(420, 100));

		jTextArea1.setColumns(20);
		jTextArea1.setRows(5);
		jScrollPane1.setViewportView(jTextArea1);

		javax.swing.GroupLayout jPanel38Layout = new javax.swing.GroupLayout(
				jPanel38);
		jPanel38.setLayout(jPanel38Layout);
		jPanel38Layout.setHorizontalGroup(jPanel38Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 420,
				Short.MAX_VALUE));
		jPanel38Layout.setVerticalGroup(jPanel38Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel38Layout.createSequentialGroup().addComponent(
						jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE,
						101, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE,
								Short.MAX_VALUE)));

		jPanel36.add(jPanel38);

		jPanel39.setMaximumSize(new java.awt.Dimension(800, 240));
		jPanel39.setPreferredSize(new java.awt.Dimension(10, 100));

		javax.swing.GroupLayout jPanel39Layout = new javax.swing.GroupLayout(
				jPanel39);
		jPanel39.setLayout(jPanel39Layout);
		jPanel39Layout.setHorizontalGroup(jPanel39Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 66,
				Short.MAX_VALUE));
		jPanel39Layout.setVerticalGroup(jPanel39Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 100,
				Short.MAX_VALUE));

		jPanel36.add(jPanel39);

		jPanel27.add(jPanel36);

		jPanel31.setMaximumSize(new java.awt.Dimension(32767, 50));
		jPanel31.setPreferredSize(new java.awt.Dimension(0, 50));
		jPanel31.setLayout(new javax.swing.BoxLayout(jPanel31,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel23.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel23.setText("\u5907\u4efd\u76ee\u7684\u5377");
		jLabel23.setMaximumSize(new java.awt.Dimension(240, 21));
		jLabel23.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel31.add(jLabel23);

		jButton15.setFont(new java.awt.Font("宋体", 0, 14));
		jButton15.setText("\u9009\u62e9");
		jButton15.setMaximumSize(new java.awt.Dimension(80, 25));
		jButton15.setPreferredSize(new java.awt.Dimension(70, 25));
		jButton15.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton15ActionPerformed(evt);
			}
		});
		jPanel31.add(jButton15);

		jTextField9.setMaximumSize(new java.awt.Dimension(340, 21));
		jPanel31.add(jTextField9);

		jPanel27.add(jPanel31);

		jPanel32.setMaximumSize(new java.awt.Dimension(33007, 50));
		jPanel32.setPreferredSize(new java.awt.Dimension(156, 50));
		jPanel32.setLayout(new javax.swing.BoxLayout(jPanel32,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel24.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel24.setText("\u5907\u4efd\u7c7b\u578b");
		jLabel24.setMaximumSize(new java.awt.Dimension(240, 21));
		jLabel24.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel32.add(jLabel24);

		jPanel40.setMaximumSize(new java.awt.Dimension(480, 40));
		jPanel40.setPreferredSize(new java.awt.Dimension(120, 100));
		jPanel40.setLayout(new javax.swing.BoxLayout(jPanel40,
				javax.swing.BoxLayout.LINE_AXIS));

		jCheckBox5.setFont(new java.awt.Font("宋体", 0, 14));
		jCheckBox5.setText("\u5168\u5907\u4efd");
		jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox5ActionPerformed(evt);
			}
		});
		jPanel40.add(jCheckBox5);

		jCheckBox6.setFont(new java.awt.Font("宋体", 0, 14));
		jCheckBox6.setText("\u589e\u91cf\u5907\u4efd");
		jCheckBox6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox6ActionPerformed(evt);
			}
		});
		jPanel40.add(jCheckBox6);

		jCheckBox7.setFont(new java.awt.Font("宋体", 0, 14));
		jCheckBox7.setText("\u5dee\u5f02\u5907\u4efd");
		jCheckBox7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jCheckBox7ActionPerformed(evt);
			}
		});
		jPanel40.add(jCheckBox7);

		jPanel32.add(jPanel40);

		jPanel27.add(jPanel32);

		jPanel33.setMaximumSize(new java.awt.Dimension(32674, 50));
		jPanel33.setPreferredSize(new java.awt.Dimension(220, 50));
		jPanel33.setLayout(new javax.swing.BoxLayout(jPanel33,
				javax.swing.BoxLayout.LINE_AXIS));

		jLabel25.setFont(new java.awt.Font("宋体", 0, 14));
		jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
		jLabel25.setText("\u6267\u884c\u65e5\u671f");
		jLabel25.setMaximumSize(new java.awt.Dimension(240, 21));
		jLabel25.setPreferredSize(new java.awt.Dimension(120, 21));
		jPanel33.add(jLabel25);

		jPanel41.setMaximumSize(new java.awt.Dimension(480, 23));
		jPanel41.setPreferredSize(new java.awt.Dimension(120, 50));
		jPanel41.setLayout(new javax.swing.BoxLayout(jPanel41,
				javax.swing.BoxLayout.LINE_AXIS));

		jRadioButton3.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton3.setText("\u661f\u671f\u4e00");
		jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton3ActionPerformed(evt);
			}
		});
		jPanel41.add(jRadioButton3);

		jRadioButton4.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton4.setText("\u661f\u671f\u4e8c");
		jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton4ActionPerformed(evt);
			}
		});
		jPanel41.add(jRadioButton4);

		jRadioButton5.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton5.setText("\u661f\u671f\u4e09");
		jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton5ActionPerformed(evt);
			}
		});
		jPanel41.add(jRadioButton5);

		jRadioButton6.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton6.setText("\u661f\u671f\u56db");
		jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton6ActionPerformed(evt);
			}
		});
		jPanel41.add(jRadioButton6);

		jPanel33.add(jPanel41);

		jPanel27.add(jPanel33);

		jPanel34.setMaximumSize(new java.awt.Dimension(32767, 40));
		jPanel34.setLayout(new javax.swing.BoxLayout(jPanel34,
				javax.swing.BoxLayout.LINE_AXIS));

		jPanel42.setMaximumSize(new java.awt.Dimension(240, 21));
		jPanel42.setPreferredSize(new java.awt.Dimension(120, 21));

		javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(
				jPanel42);
		jPanel42.setLayout(jPanel42Layout);
		jPanel42Layout.setHorizontalGroup(jPanel42Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 240,
				Short.MAX_VALUE));
		jPanel42Layout.setVerticalGroup(jPanel42Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 21,
				Short.MAX_VALUE));

		jPanel34.add(jPanel42);

		jPanel43.setMaximumSize(new java.awt.Dimension(240, 21));
		jPanel43.setMinimumSize(new java.awt.Dimension(120, 25));
		jPanel43.setPreferredSize(new java.awt.Dimension(0, 21));
		jPanel43.setLayout(new javax.swing.BoxLayout(jPanel43,
				javax.swing.BoxLayout.LINE_AXIS));

		jRadioButton7.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton7.setText("\u661f\u671f\u4e94");
		jRadioButton7.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton7ActionPerformed(evt);
			}
		});
		jPanel43.add(jRadioButton7);

		jRadioButton8.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton8.setText("\u661f\u671f\u516d");
		jRadioButton8.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton8ActionPerformed(evt);
			}
		});
		jPanel43.add(jRadioButton8);

		jRadioButton9.setFont(new java.awt.Font("宋体", 0, 14));
		jRadioButton9.setText("\u661f\u671f\u65e5");
		jRadioButton9.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jRadioButton9ActionPerformed(evt);
			}
		});
		jPanel43.add(jRadioButton9);

		jPanel34.add(jPanel43);

		jPanel44.setMaximumSize(new java.awt.Dimension(240, 21));
		jPanel44.setPreferredSize(new java.awt.Dimension(120, 21));

		javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(
				jPanel44);
		jPanel44.setLayout(jPanel44Layout);
		jPanel44Layout.setHorizontalGroup(jPanel44Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 240,
				Short.MAX_VALUE));
		jPanel44Layout.setVerticalGroup(jPanel44Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 21,
				Short.MAX_VALUE));

		jPanel34.add(jPanel44);

		jPanel27.add(jPanel34);

		jButton16.setFont(new java.awt.Font("宋体", 0, 14));
		jButton16.setText("\u4fdd\u5b58");
		jButton16.setPreferredSize(new java.awt.Dimension(70, 25));
		jButton16.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton16ActionPerformed(evt);
			}
		});

		jButton17.setFont(new java.awt.Font("宋体", 0, 14));
		jButton17.setText("\u53d6\u6d88");
		jButton17.setPreferredSize(new java.awt.Dimension(70, 25));
		jButton17.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jButton17ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel35Layout = new javax.swing.GroupLayout(
				jPanel35);
		jPanel35.setLayout(jPanel35Layout);
		jPanel35Layout
				.setHorizontalGroup(jPanel35Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel35Layout
										.createSequentialGroup()
										.addGap(241, 241, 241)
										.addComponent(
												jButton16,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(
												jButton17,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(335, Short.MAX_VALUE)));
		jPanel35Layout
				.setVerticalGroup(jPanel35Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel35Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel35Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																jButton16,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																jButton17,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addContainerGap(37, Short.MAX_VALUE)));

		jPanel27.add(jPanel35);
		jPanel27.add(jSeparator6);

		getContentPane().add(jPanel27);

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		System.exit(0);
	}

	private void formWindowClosing(java.awt.event.WindowEvent evt) {
		// TODO add your handling code here:
		this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
	}

	private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		backupJobname = jTextField8.getText().trim().toString();
		backupVolume = jTextField9.getText().trim().toString();
		backupDate = sdf.format(new Date());
		backupSrc = jTextArea1.getText().trim();
		BackupClient bc = new BackupClient();
		String configfile;
		try {
			if (!backupJobname.equals("") && !backupSrc.equals("")
					&& !backupVolume.equals("")) {
				backupFilesLength = bc.getBackupSize(backupSrc);
				bc.initBackupSize();
				backupJobFilesCount = bc.getBackupJobFilesCount();
				bc.setBackupJobFilesCount(0);

				try {
					configfile = ba.writeBackupConfigToXML(backupJobname,
							backupSrc, weekp, backupVolume, backupFilesLength,
							backupJobFilesCount);
				} catch (java.text.ParseException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			} else {
				JOptionPane.showMessageDialog(null,
						"Absent some information ,please input it agian!");
			}
		} catch (ParserConfigurationException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}

		TempStorage.backupName = backupJobname;
		TempStorage.backupSrc = backupSrc;
		TempStorage.backupVolume = backupVolume;
		TempStorage.backupUserName = System.getProperty("user.name");

		MainFrame.initbackuptaskinfo();
		System.out.println("backup job record finished!");
		//		// write backup config information to mysql
		//		int compresstype = -1;
		//		bc.writeBackupConfigToSQL(backupJobname, backupSrc, backupDate,
		//				backupVolume, compresstype, backupFilesLength);
		//		bc.setBackupSize();

		this.dispose();

	}

	private void jRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton9.isSelected()) {
			weekp.Sunday = this.type;
		}
	}

	private void jRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton8.isSelected()) {
			weekp.Saturday = this.type;
		}
	}

	private void jRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton7.isSelected()) {
			weekp.Friday = this.type;
		}
	}

	private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton6.isSelected()) {
			weekp.Thursday = this.type;
		}
	}

	private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton5.isSelected()) {
			weekp.Wednesday = this.type;
		}
	}

	private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton4.isSelected()) {
			weekp.Tuesday = this.type;
		}
	}

	private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jRadioButton3.isSelected()) {
			weekp.Monday = this.type;
		}
	}

	private void jCheckBox7ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jCheckBox7.isSelected()) {
			jCheckBox5.setSelected(false);
			jCheckBox6.setSelected(false);

			type = 2;
		}
	}

	private void jCheckBox6ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jCheckBox6.isSelected()) {
			jCheckBox5.setSelected(false);
			jCheckBox7.setSelected(false);

			type = 1;
		}
	}

	private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		if (jCheckBox5.isSelected()) {
			jCheckBox6.setSelected(false);
			jCheckBox7.setSelected(false);

			type = 0;
		}
	}

	private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		new VolumeInfoShowThread().start();
		jTextField9.setText(TempStorage.vol_name);
	}

	private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
		File[] file = null;
		jFileChooser1.setMultiSelectionEnabled(true);
		jFileChooser1.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);//set file selection mode:we can select file and directory.
		int returnVal = jFileChooser1.showOpenDialog(new javax.swing.JFrame());
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			file = jFileChooser1.getSelectedFiles();
			for(File jf: file){
				jTextArea1.append(jf.getAbsolutePath() + "\n");
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new CreateBackupJob().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton14;
	private javax.swing.JButton jButton15;
	private javax.swing.JButton jButton16;
	private javax.swing.JButton jButton17;
	private javax.swing.JCheckBox jCheckBox5;
	private javax.swing.JCheckBox jCheckBox6;
	private javax.swing.JCheckBox jCheckBox7;
	private javax.swing.JFileChooser jFileChooser1;
	private javax.swing.JLabel jLabel20;
	private javax.swing.JLabel jLabel21;
	private javax.swing.JLabel jLabel22;
	private javax.swing.JLabel jLabel23;
	private javax.swing.JLabel jLabel24;
	private javax.swing.JLabel jLabel25;
	private javax.swing.JPanel jPanel27;
	private javax.swing.JPanel jPanel28;
	private javax.swing.JPanel jPanel29;
	private javax.swing.JPanel jPanel30;
	private javax.swing.JPanel jPanel31;
	private javax.swing.JPanel jPanel32;
	private javax.swing.JPanel jPanel33;
	private javax.swing.JPanel jPanel34;
	private javax.swing.JPanel jPanel35;
	private javax.swing.JPanel jPanel36;
	private javax.swing.JPanel jPanel37;
	private javax.swing.JPanel jPanel38;
	private javax.swing.JPanel jPanel39;
	private javax.swing.JPanel jPanel40;
	private javax.swing.JPanel jPanel41;
	private javax.swing.JPanel jPanel42;
	private javax.swing.JPanel jPanel43;
	private javax.swing.JPanel jPanel44;
	private javax.swing.JRadioButton jRadioButton3;
	private javax.swing.JRadioButton jRadioButton4;
	private javax.swing.JRadioButton jRadioButton5;
	private javax.swing.JRadioButton jRadioButton6;
	private javax.swing.JRadioButton jRadioButton7;
	private javax.swing.JRadioButton jRadioButton8;
	private javax.swing.JRadioButton jRadioButton9;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JSeparator jSeparator6;
	private javax.swing.JSeparator jSeparator8;
	private javax.swing.JTextArea jTextArea1;
	private javax.swing.JTextField jTextField8;
	private static javax.swing.JTextField jTextField9;
	// End of variables declaration//GEN-END:variables
}